# Configurações do servidor
server:
  port: 8080

# Configurações do banco de dados H2 (em memória)
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

# Configurações do JPA (se estiver usando)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update